### ISSUE TITLE
Game unwinnable if (1, 1) is red

### ISSUE THREAD

**Issue by jjayeon** [jjayeon/breadcrumbs#8]
the second move for the ant will always be onto tile (1, 1) (if upper left is 0, 0), so if (1, 1) turns out red then the problem is unsolvable.  we may just hard-code not red for (1, 1).

there are other unwinnable states too --- is it worth detecting and compensating for them, or should we just have the user restart?

**Comment by mgsium** [comment]
I added a (1,1) check so a red tile can't be assigned there. I'll close this issue and open another for unwinnable states in general. Accounting for all the others would be more difficult than it's worth at the moment, so I'll give it the _wontfix_ tag for now.
